name: Config Split
type: module
description: Configuration transformer for importing and exporting split config
core_version_requirement: ^8.8 || ^9
package: Config
configure: entity.config_split.collection
